### ISSUE TITLE
failed to build on windows

### ISSUE THREAD

**Issue by ghost** [litespeedtech/lsquic#488]
https://github.com/zzwxh/lsquic-build/actions/runs/7296502893/job/19884415147
build.yaml:
```
name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3

    - name: Cache boringssl
      id: cache-boringssl
      uses: actions/cache@v3
      with:
        path: boringssl
        key: boringssl-cache-0009

    - name: Build boringssl
      if: steps.cache-boringssl.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && powershell -File build-boringssl.ps1

    - name: Build lsquic
      shell: cmd
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && powershell -File build-lsquic.ps1
```
build-boringssl.ps1:
```
git clone https://boringssl.googlesource.com/boringssl
cd boringssl
git checkout cf8d3ad3cea51cf7184307d54f465da62b7d8408
cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DOPENSSL_NO_ASM=1 .
msbuild /m ALL_BUILD.vcxproj
```
```
Build FAILED.

       "D:\a\lsquic-build\lsquic-build\boringssl\ALL_BUILD.vcxproj" (default target) (1) ->
       "D:\a\lsquic-build\lsquic-build\boringssl\crypto\crypto.vcxproj" (default target) (13) ->
       (ClCompile target) -> 
         D:\a\lsquic-build\lsquic-build\boringssl\crypto\bio\connect.c(488,29): warning C4191: 'type cast': unsafe conversion from 'bio_info_cb' to 'int (__cdecl *)(const bio_st *,int,int)' [D:\a\lsquic-build\lsquic-build\boringssl\crypto\crypto.vcxproj]


       "D:\a\lsquic-build\lsquic-build\boringssl\ALL_BUILD.vcxproj" (default target) (1) ->
       "D:\a\lsquic-build\lsquic-build\boringssl\crypto\crypto.vcxproj" (default target) (13) ->
       (ClCompile target) -> 
         D:\a\lsquic-build\lsquic-build\boringssl\crypto\bio\connect.c(488,29): error C2220: the following warning is treated as an error [D:\a\lsquic-build\lsquic-build\boringssl\crypto\crypto.vcxproj]

    1 Warning(s)
    1 Error(s)
```
